name: student management restapi workflow
on: [push,fork]
jobs:
  run_hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: "Echo a string"
        run: echo "Testing this workflow"


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}