name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: #provide a button on ui can click to re-run workflow

jobs:
  Hello_world: #job name
    name: hello world job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hellow world
        run: echo "Hello world"
        shell: bash

  GoodBye:
    name: good bye world
    runs-on: ubuntu-latest
    steps:
      - name: Good Bye world
        run: echo "GoodBye World"
        shell: bash

    

      
    